#!/usr/bin/env python3
"""State Machine scaffolding tool.

Reads a states.yaml definition and generates a type-safe State Machine class
(Python enum + transition matrix) that throws exceptions on invalid moves.

Usage:
    python ~/.claude/tools/software-design/sm/scaffold_states.py states.yaml output_dir
    python ~/.claude/tools/software-design/sm/scaffold_states.py states.yaml --stdout
"""
from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def generate_state_enum(entity: str, states: list[str], transitions: list[dict]) -> str:
    """Generate Python state machine code from YAML definition."""
    state_names = ", ".join(f'{s.upper()} = "{s}"' for s in states)
    
    transition_lines = []
    for t in transitions:
        src = t["source"].upper()
        event = t["event"]
        target = t["target"].upper()
        guard = t.get("guard", "")
        action = t.get("action", "")
        
        if guard:
            transition_lines.append(f'    ({src.upper()!r}, {event!r}, {target.upper()!r}, {guard!r}, {action!r})')
        else:
            transition_lines.append(f'    ({src.upper()!r}, {event!r}, {target.upper()!r}, None, {action!r})')
    
    transitions_str = ",\n".join(transition_lines)
    
    return textwrap.dedent(f'''\
        """Auto-generated State Machine for {entity}.
        
        Generated by scaffold_states.py from states.yaml.
        DO NOT EDIT MANUALLY — regenerate from YAML definition.
        """
        from __future__ import annotations
        
        from enum import Enum
        from typing import Dict, List, Optional, Set, Tuple
        
        
        class {entity}State(str, Enum):
            """Valid states for {entity} lifecycle."""
            {state_names}
        
        
        # Transition matrix: (source, event, target, guard, action)
        _TRANSITIONS: List[Tuple[str, str, str, Optional[str], Optional[str]]] = [
        {transitions_str},
        ]
        
        # Lookup: (source_state, event) -> list of (target, guard, action)
        _TRANSITION_MAP: Dict[Tuple[str, str], List[Tuple[str, Optional[str], Optional[str]]]] = {{
            (src, evt): [] for src, evt, _, _, _ in _TRANSITIONS
        }}
        
        for src, evt, tgt, guard, action in _TRANSITIONS:
            _TRANSITION_MAP[(src, evt)].append((tgt, guard, action))
        
        
        class InvalidTransitionError(Exception):
            """Raised when an invalid state transition is attempted."""
            def __init__(self, state: str, event: str):
                self.state = state
                self.event = event
                super().__init__(f"Invalid transition: {{state}} --[{{event}}]--> (no matching transition)")
        
        
        def can_transition_to(current: {entity}State, event: str) -> bool:
            """Check if a transition is valid from the current state."""
            key = (current.value, event)
            return key in _TRANSITION_MAP and len(_TRANSITION_MAP[key]) > 0
        
        
        def get_valid_events(current: {entity}State) -> Set[str]:
            """Get all valid events from the current state."""
            return {{evt for (src, evt) in _TRANSITION_MAP if src == current.value}}
        
        
        def get_valid_targets(current: {entity}State, event: str) -> List[{entity}State]:
            """Get all valid target states for a given event from current state."""
            key = (current.value, event)
            if key not in _TRANSITION_MAP:
                return []
            return [{entity}State(tgt) for tgt, _, _ in _TRANSITION_MAP[key]]
        
        
        def transition(current: {entity}State, event: str, guard_check: Optional[callable] = None) -> {entity}State:
            """Execute a state transition.
            
            Args:
                current: Current state
                event: Event triggering the transition
                guard_check: Optional callable that returns True if guard passes
            
            Returns:
                The new state after transition
            
            Raises:
                InvalidTransitionError: If transition is not valid
            """
            key = (current.value, event)
            if key not in _TRANSITION_MAP or not _TRANSITION_MAP[key]:
                raise InvalidTransitionError(current.value, event)
            
            candidates = _TRANSITION_MAP[key]
            
            for target, guard, action in candidates:
                if guard is None or (guard_check and guard_check(guard)):
                    print(f"[EVENT] {{current.value}} --[{{event}}]--> {{target}}")
                    return {entity}State(target)
            
            raise InvalidTransitionError(current.value, event)
        
        
        def get_all_states() -> List[{entity}State]:
            """Get all valid states."""
            return list({entity}State)
        
        
        def get_all_transitions() -> List[Tuple[{entity}State, str, {entity}State]]:
            """Get all valid transitions."""
            return [({entity}State(src), evt, {entity}State(tgt)) for src, evt, tgt, _, _ in _TRANSITIONS]
    ''')


def generate_test(entity: str, states: list[str], transitions: list[dict]) -> str:
    """Generate pytest tests for the state machine."""
    first_state = states[0].upper() if states else "INITIAL"
    first_event = transitions[0]["event"] if transitions else "test_event"
    first_target = transitions[0]["target"].upper() if transitions else "NEXT"
    
    return textwrap.dedent(f'''\
        """Tests for {entity} State Machine.
        
        Auto-generated by scaffold_states.py. Add custom tests as needed.
        """
        import pytest
        from {entity.lower()}_state import (
            {entity}State,
            InvalidTransitionError,
            can_transition_to,
            get_valid_events,
            transition,
        )
        
        
        class Test{entity}StateMachine:
            def test_valid_transition(self):
                result = transition({entity}State.{first_state}, "{first_event}")
                assert result == {entity}State.{first_target}
            
            def test_invalid_transition_raises(self):
                with pytest.raises(InvalidTransitionError):
                    transition({entity}State.{first_state}, "NONEXISTENT_EVENT")
            
            def test_can_transition_to_valid(self):
                assert can_transition_to({entity}State.{first_state}, "{first_event}")
            
            def test_can_transition_to_invalid(self):
                assert not can_transition_to({entity}State.{first_state}, "NONEXISTENT_EVENT")
            
            def test_get_valid_events(self):
                events = get_valid_events({entity}State.{first_state})
                assert "{first_event}" in events
    ''')


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate state machine code from YAML definition"
    )
    parser.add_argument("yaml_path", help="Path to states.yaml")
    parser.add_argument("output_dir", nargs="?", default=".", help="Output directory")
    parser.add_argument("--stdout", action="store_true", help="Print to stdout instead of file")
    parser.add_argument("--no-test", action="store_true", help="Skip test generation")
    args = parser.parse_args()
    
    yaml_path = Path(args.yaml_path)
    if not yaml_path.exists():
        print(f"Error: {yaml_path} not found", file=sys.stderr)
        return 1
    
    data = yaml.safe_load(yaml_path.read_text())
    entity = data.get("entity", "Entity")
    states = data.get("states", [])
    transitions = data.get("transitions", [])
    
    if not states:
        print("Error: no states defined in YAML", file=sys.stderr)
        return 1
    
    code = generate_state_enum(entity, states, transitions)
    
    if args.stdout:
        print(code)
        if not args.no_test:
            print("\n" + "=" * 60 + "\n")
            print(generate_test(entity, states, transitions))
        return 0
    
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # Write state machine
    sm_file = out_dir / f"{entity.lower()}_state.py"
    sm_file.write_text(code)
    print(f"[SCAFFOLD-STATES] Generated: {sm_file}")
    
    # Write tests
    if not args.no_test:
        test_file = out_dir / f"test_{entity.lower()}_state.py"
        test_file.write_text(generate_test(entity, states, transitions))
        print(f"[SCAFFOLD-STATES] Generated: {test_file}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
