' Section: cd_section_iface_composition.puml

package "composition_root" as WIRE #EDE7F6/5E35B1 {

  class "**ApplicationContainer**" as ApplicationContainer <<Composition>> #EDE7F6/5E35B1 {
    + build(): ApplicationContainer
    + rest_app(): RestApplication
    + cli_app(): CliApplication
    + tui_app(): TuiApplication
  }

  class "**PortBindings**" as PortBindings <<Composition>> #EDE7F6/5E35B1 {
    + bind_directive_ports()
    + bind_compile_ports()
    + bind_inspection_ports()
    + bind_finding_ports()
    + bind_artifact_ports()
    + bind_gate(DenialAuditPort)
  }

  class "**OutboxDrainScheduler**" as OutboxDrainScheduler <<Composition>> #EDE7F6/5E35B1 {
    + start()
    + tick(): int
    --
    <<invokes>> DrainOutbox
  }
}

