#!/usr/bin/env bash
# Environment / build artifact cleanser for this service only.
#
# Removes temporary generated files that:
# - pollute the source tree
# - clutter VS Code explorer / search
# - can cause stale cache issues (pyc, egg-info, ruff/pytest caches, etc.)
#
# Safe to run anytime. Does NOT touch:
# - your conda environment
# - source code under src/ or tests/
# - data/ models/ or real artifacts
# - .env* files (except they are already gitignored)
#
# Usage:
#   bash scripts/clean.sh
#   bash scripts/clean.sh --dry-run
#
# Recommended: automatically invoked from .githooks/pre-commit

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

DRY_RUN="${1:-}"

log() { printf 'clean: %s\n' "$*" >&2; }
do_rm() {
  if [[ "$DRY_RUN" == "--dry-run" ]]; then
    echo "  (dry) rm -rf $*"
  else
    rm -rf "$@"
  fi
}

cd "${SERVICE_ROOT}"

log "Cleaning temporary python/build artifacts (scoped to this service)..."

# Python bytecode and caches
find . -type d -name '__pycache__' -exec sh -c 'for d; do [ -d "$d" ] && do_rm "$d"; done' sh {} + 2>/dev/null || true
find . -type f \( -name '*.py[co]' -o -name '*$.py.class' \) -delete 2>/dev/null || true

# Packaging metadata (egg-info is regenerated by pip install -e .)
# Note: with src layout it can sometimes appear under src/ — we nuke all of them.
find . -type d -name '*.egg-info' -exec sh -c 'for d; do [ -d "$d" ] && do_rm "$d"; done' sh {} + 2>/dev/null || true
do_rm -rf src/model_management_service.egg-info model_management_service.egg-info 2>/dev/null || true
do_rm -f .eggs/ MANIFEST 2>/dev/null || true

# Build / dist artifacts
do_rm -rf build/ dist/ 2>/dev/null || true

# Tool caches
do_rm -rf .ruff_cache/ .pytest_cache/ .mypy_cache/ .hypothesis/ .nox/ .tox/ 2>/dev/null || true

# Coverage
do_rm -f .coverage .coverage.* coverage.xml htmlcov/ 2>/dev/null || true

# Other common temp
do_rm -rf .cache/ *.log *.tmp 2>/dev/null || true

log "Clean complete. Tree is fresh."
if [[ "$DRY_RUN" != "--dry-run" ]]; then
  log "Tip: re-run 'pip install -e \"[dev]\"' if you want fresh egg metadata."
fi
