' ============================================================
' Section: uc_section_inspection.puml
' Group SSoT: $TITLE_APP_INS == C4 inspections_application
' Leaves: package UC_INS_* == class <<Use Case>>
' ============================================================

rectangle "$GRP_APP_INS" as GRP_INS $UC_PKG_APPLICATION {

  usecase "$UC_NAME_CREATE_INSPECTION" as UC_INS_CREATE $CA_FILL_APPLICATION
  usecase "$UC_NAME_GET_INSPECTION" as UC_INS_GET $CA_FILL_APPLICATION
  usecase "$UC_NAME_RUN_INSPECTION_PIPELINE" as UC_INS_PIPE $CA_FILL_APPLICATION

  UC_INS_CREATE ..> UC_INS_PIPE : <<include>>
}
